Repository Lumieducation/H5P-Nodejs-library, pull requests merged in 2019-10, with the labels that each got.

#147 Add e2e-test for player
  .circleci/config.yml
  .gitignore
  jest.config.js
  package-lock.json
  package.json
  src/H5PEditor.ts
  src/H5PPlayer.ts
  src/PackageManager.ts
  src/types.ts
  test/H5PPlayer.renderHtmlPage.test.ts
  test/e2e/H5PPlayer.DisplayContent.test.ts
Labels: [type] test, continuous integration, help wanted

#118 Content export functionality (closes #113)
  examples/express.js
  index.js
  package-lock.json
  package.json
  src/ContentManager.ts
  src/ContentTypeInformationRepository.ts
  src/DependencyGetter.ts
  src/FileContentStorage.ts
  src/FileLibraryStorage.ts
  src/H5PEditor.ts
  src/LibraryManager.ts
  src/PackageExporter.ts
  src/PackageImporter.ts
  src/types.ts
  test/DependencyGetter.test.ts
  test/FileContentStorage.test.ts
  test/LibraryManager.test.ts
  test/PackageExporter.test.ts
  test/PackageImporter.test.ts
  test/data/library-dependency/Lib1-1.0/library.json
  test/data/library-dependency/Lib2-1.0/library.json
  test/data/library-dependency/Lib3-1.0/library.json
  test/data/library-dependency/Lib4-1.0/library.json
  test/data/library-dependency/Lib5-1.0/library.json
  test/e2e/H5PPlayer.DisplayContent.test.ts
Labels: [status] needs reviewer, [type] feature

#157 fixed metadata persistence (closes #152)
  src/ContentManager.ts
  src/FileContentStorage.ts
  src/H5PEditor.ts
  src/H5PPlayer.ts
  src/PackageExporter.ts
  src/types.ts
  test/FileContentStorage.test.ts
Labels: [type] bug

#160 Added functionality to get language files for text overrides
  examples/express.js
  src/H5PEditor.ts
Labels: [status] needs reviewer, [type] feature, enhancement

#149 Moved temporary directory creation to global temp directory
  .gitignore
  test/ContentTypeInformationRepository.test.ts
Labels: [status] needs reviewer, enhancement

#162 Typescript references now also work in tests
  .gitignore
  package.json
  tsconfig.base.json
  tsconfig.build.json
  tsconfig.json
Labels: enhancement

#161 Missing libraries are now dealt with accordingly (closes #159)
  examples/express.js
  src/DependencyGetter.ts
  src/FileLibraryStorage.ts
  src/H5PEditor.ts
  src/Library.ts
  test/Library.test.ts
Labels: [status] needs reviewer, [type] bug

#156 Move implementation files from src to examples
  .gitignore
  examples/express.js
  examples/implementation/EditorConfig.ts
  examples/implementation/FileContentStorage.ts
  examples/implementation/FileLibraryStorage.ts
  examples/implementation/InMemoryStorage.ts
  examples/implementation/JsonStorage.ts
  examples/implementation/User.ts
  index.js
  package.json
  scripts/update-real-content-type-cache.ts
  src/ContentTypeCache.ts
  src/ContentTypeInformationRepository.ts
  src/H5PEditor.ts
  src/PackageExporter.ts
  src/PackageImporter.ts
  src/PackageValidator.ts
  src/types.ts
  test/ContentTypeCache.test.ts
  test/ContentTypeInformationRepository.test.ts
  test/DependencyGetter.test.ts
  test/EditorConfig.test.ts
  test/FileContentStorage.test.ts
  test/H5PPlayer.renderHtmlPage.test.ts
  test/JsonStorage.test.ts
  test/LibraryManager.test.ts
  test/PackageExporter.test.ts
  test/PackageImporter.test.ts
  test/PackageValidator.test.ts
  test/e2e/H5PPlayer.DisplayContent.test.ts
  test/getLibraryData.test.ts
  test/getLibraryOverview.test.ts
  test/validate-hub-examples.test.ts
  tsconfig.base.json
  tsconfig.build.json
  tsconfig.json
Labels: [status] needs reviewer, enhancement

#165 Allow undefined preloadedDependencies for libraries (closes #164)
  src/H5PEditor.ts
  src/Library.ts
Labels: [status] needs reviewer, [type] bug

#172 docs: Update CONTRIBUTING with conventional commit msg
  .github/CONTRIBUTING.md
Labels: documentation

#177 feat(example): added link to example player to download packages
  examples/express.js
  index.js
  src/H5PEditor.ts
  src/H5PPlayer.ts
  src/PackageExporter.ts
  src/renderers/player.ts
  test/H5PPlayer.renderHtmlPage.test.ts
Labels: [type] feature

#176 refactor(H5PEditor)!: Moved user from constructor of H5PEditor to method calls (closes issue 158)
  README.md
  examples/express.js
  src/ContentTypeInformationRepository.ts
  src/H5PEditor.ts
  test/ContentTypeInformationRepository.test.ts
  test/getLibraryData.test.ts
  test/getLibraryOverview.test.ts
Labels: BREAKING CHANGE, refactor

#173 feat(log): Add logging module (closes #153)
  package-lock.json
  package.json
  src/ContentManager.ts
  src/ContentTypeCache.ts
  src/ContentTypeInformationRepository.ts
  src/DependencyGetter.ts
  src/H5PEditor.ts
  src/H5PPlayer.ts
  src/LibraryManager.ts
  src/PackageExporter.ts
  src/PackageImporter.ts
  src/PackageValidator.ts
  src/TranslationService.ts
  src/helpers/Logger.ts
Labels: [status] in progress, [type] feature

#187 refactor(types)!: Made naming and interface usage more consistent (closes #119)
  examples/express.js
  examples/implementation/FileLibraryStorage.ts
  index.js
  src/ContentManager.ts
  src/ContentTypeCache.ts
  src/ContentTypeInformationRepository.ts
  src/DependencyGetter.ts
  src/H5PEditor.ts
  src/H5PPlayer.ts
  src/HubContentType.ts
  src/InstalledLibrary.ts
  src/Library.ts
  src/LibraryManager.ts
  src/LibraryName.ts
  src/PackageExporter.ts
  src/PackageValidator.ts
  src/types.ts
  test/DependencyGetter.test.ts
  test/LibraryManager.test.ts
  test/LibraryName.test.ts
Labels: [status] needs reviewer, refactor

#191 fix: remove deprecated h5p-editor.js (closes #188)
  src/H5PEditor.ts
Labels: [type] bug

#189 feature(temporary-files)!: Added temporary file manager (#87)
  examples/express.js
  examples/implementation/DirectoryTemporaryFileStorage.ts
  examples/implementation/EditorConfig.ts
  package-lock.json
  package.json
  src/H5PEditor.ts
  src/TemporaryFileManager.ts
  src/types.ts
  test/TemporaryFileManager.test.ts
  test/getLibraryData.test.ts
  test/getLibraryOverview.test.ts
  tslint.json
Labels: [status] needs reviewer, enhancement

#204 Docs: Improved and updated documentation
  README.md
  docs/endpoints.md
  docs/h5p-editor-constructor.md
  examples/implementation/EditorConfig.ts
  examples/implementation/FileContentStorage.ts
  examples/implementation/FileLibraryStorage.ts
  src/InstalledLibrary.ts
  src/types.ts
Labels: [status] needs reviewer, documentation

#202 feat(editor)!: URLs hardcoded into data structures are now resolved correctly
  examples/express.js
  src/ContentTypeInformationRepository.ts
  src/H5PEditor.ts
  src/LibraryManager.ts
  src/types.ts
  test/getLibraryData.test.ts
  test/getLibraryOverview.test.ts
Labels: [status] needs reviewer, [type] BREAKING CHANGE, enhancement
