Repository Lumieducation/H5P-Nodejs-library, pull requests merged in 2019-11, with the labels that each got.

#218 ci(config): remove build-stage and rename install to install+build (closes #182)
  .circleci/config.yml
Labels: continuous integration

#219 feat(h5pcore): update h5p-core to v1.24
  README.md
  examples/implementation/EditorConfig.ts
  scripts/install.sh
  src/H5PPlayer.ts
  src/types.ts
  test/H5PPlayer.loadDependencies.test.ts
  test/H5PPlayer.renderHtmlPage.test.ts
Labels: [status] needs review, [type] feature

#224 fix(deps): move dev&test deps to devDeps & remove old deps
  package-lock.json
  package.json
Labels: [type] bug, npm

#222 feat(saving): Implemented content scanner
  .circleci/config.yml
  examples/implementation/DirectoryTemporaryFileStorage.ts
  jest.config.js
  jest.integration.config.js
  package-lock.json
  package.json
  scripts/download-examples.js
  src/ContentFileScanner.ts
  src/ContentManager.ts
  src/ContentScanner.ts
  src/H5PEditor.ts
  src/types.ts
  test/ContentFileScanner.test.ts
  test/ContentScanner.test.ts
  test/PackageExporter.test.ts
  test/getLibraryData.test.ts
  test/integration/ContentFileScanner.test.ts
  test/integration/PackageExporter.test.ts
  test/integration/Validation.test.ts
  tslint.json
Labels: [status] needs review, [type] feature

#230 feat: Reduced redudant core api versions and added documentation on core updates
  assets/default_editor_integration.json
  docs/core-updates.md
  examples/implementation/EditorConfig.ts
  src/H5PEditor.ts
  src/types.ts
Labels: [status] needs review, enhancement

#232 ci(config): add integration-tests to workflow (closes #228)
  .circleci/config.yml
Labels: [type] test, continuous integration

#242 feat(types): add types to released module
  index.js
  package.json
  src/index.ts
  tsconfig.base.json
Labels: [type] feature

#174 ci(release): Add semantic-release for automated releases & version-mgmt
  .circleci/config.yml
  package-lock.json
  package.json
  release.config.js
Labels: [status] blocked/hold, continuous integration, npm

#246 fix(CI): Limited parallelism in tests
  package.json
  src/ContentManager.ts
  src/ContentTypeCache.ts
  src/H5PEditor.ts
  src/LibraryManager.ts
  src/PackageExporter.ts
  test/DependencyGetter.test.ts
Labels: [status] needs review, continuous integration

#229 Feat(saving): Implement saving with temporary content files
  README.md
  examples/express.js
  examples/implementation/DirectoryTemporaryFileStorage.ts
  examples/implementation/FileContentStorage.ts
  package.json
  src/ContentFileScanner.ts
  src/ContentManager.ts
  src/ContentScanner.ts
  src/ContentStorer.ts
  src/H5PEditor.ts
  src/InstalledLibrary.ts
  src/LibraryManager.ts
  src/LibraryName.ts
  src/PackageExporter.ts
  src/TemporaryFileManager.ts
  src/helpers/ValidatorBuilder.ts
  src/types.ts
  test/ContentFileScanner.test.ts
  test/ContentManager.test.ts
  test/ContentScanner.test.ts
  test/H5PEditor.saving.test.ts
  test/PackageImporter.test.ts
  test/data/sample-content/H5P.GreetingCard-1.0/README.md
  test/data/sample-content/H5P.GreetingCard-1.0/greetingcard.css
  test/data/sample-content/H5P.GreetingCard-1.0/greetingcard.js
  test/data/sample-content/H5P.GreetingCard-1.0/language/fr.json
  test/data/sample-content/H5P.GreetingCard-1.0/language/nb.json
  test/data/sample-content/H5P.GreetingCard-1.0/library.json
  test/data/sample-content/H5P.GreetingCard-1.0/semantics.json
  test/data/sample-content/content/content.json
  test/data/sample-content/content/earth.jpg
  test/data/sample-content/h5p.json
  test/integration/ContentFileScanner.test.ts
  tslint.json
Labels: [status] needs review, enhancement

#252 test(examples): convert express-example to typescript
  .gitignore
  .npmignore
  examples/express.ts
  examples/index.ts
  package.json
  src/H5PEditor.ts
  src/H5PPlayer.ts
  src/index.ts
  tslint.json
Labels: [status] needs review

#256 fix(npm): update .npmignore to publish only relevant files
  .npmignore
Labels: [type] bug, npm

#262 doc: Added documentation on displaying log messages
  README.md
Labels: documentation

#254 Feat(copy-paste): Support copy and paste
  examples/express.ts
  examples/implementation/EditorConfig.ts
  examples/implementation/FileContentStorage.ts
  src/ContentManager.ts
  src/ContentStorer.ts
  src/H5PEditor.ts
  src/H5PPlayer.ts
  src/PackageExporter.ts
  src/PackageValidator.ts
  src/TemporaryFileManager.ts
  src/types.ts
  test/ContentManager.test.ts
  test/FileContentStorage.test.ts
  test/H5PEditor.saving.test.ts
  test/H5PPlayer.renderHtmlPage.test.ts
  test/PackageImporter.test.ts
Labels: [type] feature, enhancement

#275 docs: Added architecture documentation and improved existing one
  README.md
  docs/architecture.md
  docs/core-updates.md
  docs/editor-architecture.drawio
  docs/editor-architecture.svg
  docs/endpoints.md
  docs/h5p-editor-constructor.md
  src/H5PEditor.ts
Labels: [status] needs review, documentation

#265 fix(h5p-editor): Improved error messages
  src/ContentStorer.ts
  src/ContentTypeCache.ts
  src/ContentTypeInformationRepository.ts
  src/H5PEditor.ts
  src/LibraryManager.ts
  src/LibraryName.ts
  test/ContentTypeCache.test.ts
  test/H5PEditor.getLibraryData.test.ts
  test/H5PEditor.saving.test.ts
  test/H5PEditor.test.ts
  test/LibraryName.test.ts
Labels: [status] needs review, [type] bug

#280 feat(exports): Interfaces are now exported with type definitions
  examples/express.ts
  examples/implementation/DirectoryTemporaryFileStorage.ts
  examples/implementation/EditorConfig.ts
  examples/implementation/FileContentStorage.ts
  examples/implementation/FileLibraryStorage.ts
  examples/implementation/InMemoryStorage.ts
  examples/implementation/User.ts
  package.json
  src/index.ts
  tsconfig.build.json
Labels: [status] needs review, enhancement
