Repository Lumieducation/H5P-Nodejs-library, pull requests merged in 2019-09, with the labels that each got.

#88 fixed syntax in package.json and re-added content-type-cache.json to gitignore
  .gitignore
  package.json
  test/data/content-type-cache/real-content-types.json
Labels: bug

#91 #89 Changed path generation in validator and made test path invalid for all OSes
  src/package-validator.js
  test/file-content-storage.test.js
Labels: bug

#95 Apply library patches
  src/file-library-storage.js
  src/library-manager.js
  src/library.js
  test/data/patches/H5P.Example1-1.1.1/greetingcard.css
  test/data/patches/H5P.Example1-1.1.1/greetingcard.js
  test/data/patches/H5P.Example1-1.1.1/language/.en.json
  test/data/patches/H5P.Example1-1.1.1/language/de.json
  test/data/patches/H5P.Example1-1.1.1/library.json
  test/data/patches/H5P.Example1-1.1.1/semantics.json
  test/data/patches/H5P.Example1-1.1.2/greetingcard.css
  test/data/patches/H5P.Example1-1.1.2/greetingcard.js
  test/data/patches/H5P.Example1-1.1.2/language/.en.json
  test/data/patches/H5P.Example1-1.1.2/language/de.json
  test/data/patches/H5P.Example1-1.1.2/library.json
  test/data/patches/H5P.Example1-1.1.2/semantics.json
  test/data/patches/H5P.Example1-1.1.3 (missing js file)/greetingcard.css
  test/data/patches/H5P.Example1-1.1.3 (missing js file)/language/.en.json
  test/data/patches/H5P.Example1-1.1.3 (missing js file)/language/de.json
  test/data/patches/H5P.Example1-1.1.3 (missing js file)/library.json
  test/data/patches/H5P.Example1-1.1.3 (missing js file)/semantics.json
  test/data/patches/H5P.Example1-1.2.0/greetingcard.css
  test/data/patches/H5P.Example1-1.2.0/greetingcard.js
  test/data/patches/H5P.Example1-1.2.0/language/.en.json
  test/data/patches/H5P.Example1-1.2.0/language/de.json
  test/data/patches/H5P.Example1-1.2.0/library.json
  test/data/patches/H5P.Example1-1.2.0/semantics.json
  test/library-manager.test.js
  test/package-manager.test.js
Labels: enhancement

#94 #79 Migrated validator to yauzl
  package-lock.json
  package.json
  src/helpers/adm-zip-helpers.js
  src/package-manager.js
  src/package-validator.js
  test/validator.test.js
Labels: enhancement

#96 Fix typo in upload-package
  src/h5p-editor.js
Labels: H5P-Editor, bug

#100 listLanguages: return empty array if language folder does not exist (closes #98)
  src/library-manager.js
  test/library-manager.test.js
Labels: H5P-Editor, bug

#101 Add prettier to enforce common code-style
  package-lock.json
  package.json
  src/client/h5p-data-views.js
  src/client/h5p-toggle.js
  src/config.js
  src/content-manager.js
  src/content-type-cache.js
  src/content-type-information-repository.js
  src/content-type.js
  src/file-content-storage.js
  src/file-library-storage.js
  src/h5p-editor.js
  src/helpers/h5p-error.js
  src/helpers/stream-helpers.js
  src/helpers/string-formatter.js
  src/helpers/validator-builder.js
  src/in-memory-storage.js
  src/json-storage.js
  src/library-manager.js
  src/library.js
  src/package-manager.js
  src/package-validator.js
  src/translation-service.js
  src/user.js
  test/config.test.js
  test/content-type-cache.test.js
  test/content-type-information-repository.test.js
  test/data/libraries/H5P.Example1-1.1/greetingcard.js
  test/data/libraries/H5P.Example3-2.1/greetingcard.js
  test/data/patches/H5P.Example1-1.1.1/greetingcard.js
  test/data/patches/H5P.Example1-1.1.2/greetingcard.js
  test/data/patches/H5P.Example1-1.2.0/greetingcard.js
  test/file-content-storage.test.js
  test/getLibraryData.test.js
  test/getLibraryOverview.test.js
  test/json-storage.test.js
  test/library-manager.test.js
  test/package-manager.test.js
  test/translation-service.test.js
  test/validate-hub-examples.test.js
  test/validator.test.js
Labels: H5P-Editor

#105 Replace Travis with CircleCI
  .circleci/config.yml
  .travis.yml
Labels: H5P-Editor, continuous integration, question

#102 Add contributors in package.json
  package.json
Labels: H5P-Editor

#109 Run download-script only when installed via npm isntall (fixes #107)
  package.json
Labels: H5P-Editor, bug

#114 Run prettier for all .ts files
  package.json
  src/ContentType.ts
  src/ContentTypeCache.ts
  src/ContentTypeInformationRepository.ts
  src/FileLibraryStorage.ts
  src/InMemoryStorage.ts
  src/JsonStorage.ts
  src/helpers/StreamHelpers.ts
  test/FileContentStorage.test.ts
  test/PackageValidator.test.ts
  test/validate-hub-examples.test.ts
Labels: H5P-Editor

#115 Add CONTRIBUTING.md
  .github/CONTRIBUTING.md
Labels: H5P-Editor

#133 Add issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement

#120 Player: Add renderHtmlPage test
  test/H5PPlayer.renderHtmlPage.test.ts
Labels: H5P-Editor, [status] in progress, help wanted

#136 Update index.js to export compiled Typescript
  index.js
Labels: [type] bug

#137 Copy schemas and translations to build-folder (closes #106)
  package.json
Labels: [type] bug

#117 Merge H5P-Demo-Repository (closes #110)
  examples/config.json
  examples/examples.json
  examples/express.js
  examples/index.js
  package-lock.json
  package.json
  scripts/download-and-extract-example.sh
  scripts/download-core.sh
  scripts/download-example.sh
  scripts/install.sh
  src/client/admin.css
  src/client/h5p-editor.js
  src/client/h5p-toggle.js
  src/renderers/default.ts
Labels: H5P-Editor
