Repository Lumieducation/H5P-Nodejs-library, pull requests merged in 2019-12, with the labels that each got.

#296 fix(library management): removed id and libraryId properties of installed libraries (resolves #203)
  examples/implementation/FileLibraryStorage.ts
  src/ContentTypeInformationRepository.ts
  src/InstalledLibrary.ts
  src/LibraryManager.ts
  src/types.ts
Labels: [status] needs review

#289 fix(package upload): content of uploaded packages is now not permanently stored in the system
  README.md
  examples/express.ts
  src/ContentManager.ts
  src/ContentStorer.ts
  src/H5PEditor.ts
  src/LibraryManager.ts
  src/LibraryName.ts
  src/PackageImporter.ts
  test/ContentFileScanner.test.ts
  test/ContentScanner.test.ts
  test/H5PEditor.getLibraryData.test.ts
  test/H5PEditor.saving.test.ts
  test/H5PEditor.uploadingPackages.test.ts
  test/PackageExporter.test.ts
  test/PackageImporter.test.ts
  test/helpers/H5PEditor.ts
  test/integration/ContentFileScanner.test.ts
Labels: [status] needs review

#300 docs: Added GitHub Action to generate coverage report and send it to Coveralls
  .github/workflows/coverage.yml
  README.md
  jest.coverage.config.js
  package.json
Labels: continuous integration

#305 fix(release): add semantic-release git & github as deps
  package-lock.json
  package.json
Labels: [type] bug, npm

#309 fix(temporary file storage): streams of temporary files are now properly closed
  examples/express.ts
  src/ContentStorer.ts
  src/TemporaryFileManager.ts
  test/H5PEditor.saving.test.ts
Labels: [type] bug

#314 docs(readme): added notice that use in Windows requires bash
  README.md
Labels: [status] needs review, documentation

#313 fix(ContentTypeCache): localContentType is converted to HubContentType (fixes #308)
  src/ContentTypeCache.ts
  src/ContentTypeInformationRepository.ts
  src/HubContentType.ts
  src/types.ts
  test/ContentTypeCache.test.ts
Labels: [status] needs review, [type] bug

#321 fix(findlibraries): prevent TypeError object[key].match is not a function (fixes #320)
  src/H5PEditor.ts
  test/integration/H5PEditor.saveH5P.test.ts
Labels: [status] needs review, [type] bug

#323 fix(saving): exported packages now allows conform to the h5p.json schema (resolves #294)
  examples/express.ts
  src/ContentManager.ts
  src/ContentMetadata.ts
  src/H5PEditor.ts
  src/PackageValidator.ts
  src/schemas/h5p-schema.json
  src/types.ts
  test/FileContentStorage.test.ts
  test/H5PEditor.saving.test.ts
Labels: [status] needs review, [type] bug

#328 fix(player): the user defined integration now overwrites the default one
  src/H5PPlayer.ts
  test/H5PPlayer.integration.test.ts
Labels: [type] bug
